Repository knut-cs/Curriculum, pull requests merged in 2021-09, with the labels that each got.

#15 3학년 과목명 추가했습니다.
  src/data/web-components.js
Labels: review approved

#14 4학년 과목명을 추가했습니다.
  src/data/pwa.js
Labels: needs review

#23 과목별 설명 추가했습니다.
  src/data/accessibility.js
  src/data/fundamentals.js
  src/data/pwa.js
  src/data/web-components.js
Labels: review approved

#28 웹사이트 이미지 표시 오류 해결했습니다.
  assets/2학년/1학기/정보통신개론.svg
  assets/3학년/2학기/클라우드컴퓨팅.svg
  assets/4학년/1학기/임베디드시스템-설계.svg
  assets/4학년/2학기/병렬-및-분산시스템.svg
  assets/4학년/2학기/시스템-분석-및-설계.svg
  assets/4학년/2학기/인간과-컴퓨터상호작용.svg
Labels: review approved

#26 과목별 전필 표시했습니다.
  src/data/accessibility.js
  src/data/pwa.js
  src/data/web-components.js
  src/molecules/skill.js
Labels: needs review

#30 C언어,CAD,IoT응용 과목 이미지 표시 이슈 해결했습니다.
  assets/1학년/2학기/c언어.svg
  assets/3학년/1학기/cad.svg
  assets/4학년/2학기/iot응용.svg
  src/data/fundamentals.js
  src/data/pwa.js
  src/data/web-components.js
Labels: needs review

#31 master branch 0.4 갱신 요청합니다.
  assets/1학년/2학기/c언어.svg
  assets/2학년/1학기/정보통신개론.svg
  assets/3학년/1학기/cad.svg
  assets/3학년/2학기/클라우드컴퓨팅.svg
  assets/4학년/1학기/임베디드시스템-설계.svg
  assets/4학년/2학기/iot응용.svg
  assets/4학년/2학기/병렬-및-분산시스템.svg
  assets/4학년/2학기/시스템-분석-및-설계.svg
  assets/4학년/2학기/인간과-컴퓨터상호작용.svg
  src/data/accessibility.js
  src/data/fundamentals.js
  src/data/pwa.js
  src/data/web-components.js
  src/molecules/skill.js
Labels: needs review, upstream

#32 과목별 파일명을 추가했습니다.
  src/data.js
  src/data/1학년.js
  src/data/2학년.js
  src/data/3학년.js
  src/data/4학년.js
  src/molecules/collection.js
Labels: needs review

#35 README.md 초안 작성 완료했습니다.
  README.md
Labels: docs, review approved

#36 학과소개 추가하였습니다.
  src/util/open-help.js
Labels: review approved

#41 CONTRIBUTING.md 초안 추가, README.md 갱신
  CONTRIBUTING.md
  README.md
Labels: review approved

#43 README.md 갱신 및 필요없는 md 파일 제거하였습니다.
  CODE_OF_CONDUCT.md
  README.md
  blueprint.md
Labels: review approved

#44 master branch 1.0 갱신 요청합니다.
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  blueprint.md
Labels: review approved, upstream
